# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Full service mobile! Excellent branded apps, games and responsive websites.
baseurl: "/jekyll-mn-website" # "http://www.mobilenowgroup.com"
assetsurl: "http://www.mobilenowgroup.com/wp-content/uploads/"

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# Markdown Processors
kramdown:
  auto_ids: false

# Outputting
paginate: 4
paginate_path: "/news/page/:num/"

# Collections
collections:
  projects:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project
